In [1]:
import numpy as np
import pandas as pd

In [3]:
df3=pd.DataFrame({'name':['n1','n2','n3','n2','n1'],'score':[2,4,8,5,3]})
df3=pd.DataFrame(np.array([['n1','n2','n3','n2','n1'],[2,4,8,5,3]]).T,columns=['name','score'])
df3

  name score
0   n1     2
1   n2     4
2   n3     8
3   n2     5
4   n1     3

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
ohe=OneHotEncoder()
encoded=pd.DataFrame(ohe.fit_transform(df3[['name']]).toarray(),columns=ohe.get_feature_names_out())

In [9]:
pd.concat([df3,encoded],axis=1)

  name score  name_n1  name_n2  name_n3
0   n1     2      1.0      0.0      0.0
1   n2     4      0.0      1.0      0.0
2   n3     8      0.0      0.0      1.0
3   n2     5      0.0      1.0      0.0
4   n1     3      1.0      0.0      0.0

In [10]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le=LabelEncoder()
encoded=pd.DataFrame(le.fit_transform(df3[['name']]),columns=['name'])
encoded

C:\Users\viral\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   name
0     0
1     1
2     2
3     1
4     0

In [15]:
pd.concat([df3,encoded],axis=1)

   name score  name
0    n1     2     0
1    n2     4     1
2    n3     8     2
3    n2     5     1
4    n1     3     0

In [25]:
df4=pd.DataFrame({'score':['small','medium','small','large','medium']})

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
oe=OrdinalEncoder(categories=[['small','medium','large']])
encoded=pd.DataFrame(oe.fit_transform(df4[['score']]))
encoded

     0
0  0.0
1  1.0
2  0.0
3  2.0
4  1.0

In [29]:
pd.concat([df4,encoded],axis=1)

    score    0
0   small  0.0
1  medium  1.0
2   small  0.0
3   large  2.0
4  medium  1.0